### ISSUE TITLE
MagicPoints x64dbg

### ISSUE THREAD

**Issue by Audax48** [ThunderCls/MagicPoints#1]

**Comment by Audax48** [comment]
The files .dp32 and dp64 were not found How can I get them?

**Comment by Audax48** [comment]
Please help me to find the files

**Comment by Audax48** [comment]
Sorry

**Comment by ThunderCls** [comment]
This plugin is deprecated and replaced by xHotSpots. if you still want to download this one you can get the binary at https://github.com/ThunderCls/MagicPoints/releases

**Comment by Audax48** [comment]
Just arrived at home and checked my email......Thank you VERY MUCH for your prompt answer, I'd like to ask for another favor, where can I find xHotSpots?...I googled it but nothing found, can you help me again, PLEASE?

________________________________

**Comment by ThunderCls** [comment]
You can find it here
https://github.com/ThunderCls/xHotSpots

**Comment by Audax48** [comment]
THANKS A LOT, You are the best


________________________________
