### ISSUE TITLE
same steps as your demo video on youtube, but doesn't work for the smile-face crackme anymore

### ISSUE THREAD

**Issue by virginity-is-cool** [ThunderCls/MagicPoints#2]
win11, latest x64dbg, is it a bug?

**Comment by virginity-is-cool** [comment]
[CRACKME.zip](https://github.com/ThunderCls/MagicPoints/files/10900111/CRACKME.zip)

**Comment by ThunderCls** [comment]
This plugin is deprecated. Check the readme for more information
